# Use postgres/example user/password credentials
version: '3.1'

services:

  app:
      image: 'docker-spring-boot-postgres:latest'
      build:
        context: .
      container_name: app
      ports:
      - "8080:8080"
      depends_on:
        - db
      environment:
        spring.datasource.url: "jdbc:postgresql://db:5432/backend_test"
        spring.datasource.username: "varo"
        spring.datasource.password: "varo"
        spring.jpa.hibernate.ddl-auto: "create"
        server.address: 0.0.0.0


  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: backend_test
      POSTGRES_USER: varo
      POSTGRES_PASSWORD: varo
